version: "3.9"

services:
  backend:
    build: ./backend
    container_name: face-detection-backend
    ports:
      - "5000:5000"
    networks:
      - opencv-net

  frontend:
    build: ./frontend
    container_name: face-detection-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - opencv-net

networks:
  opencv-net:
    driver: bridge
